export enum MessageEnum {

  /**创建订阅者 */
  SUBSCRIBER_CREATE = "SUBSCRIBER_CREATE",
  /**连接订阅者 */
  SUBSCRIBER_CONNECT = "SUBSCRIBER_CONNECT",
  /**断开订阅者连接 */
  SUBSCRIBER_DISCONNECT = "SUBSCRIBER_DISCONNECT",
  /**接收发布者消息 */
  SUBSCRIBER_RECEIVE_MESSAGE = "SUBSCRIBER_RECEIVE_MESSAGE"
}
