/**
 * @description: 接收消息类型
 * @return {*}
 */
export enum MessageType {
  /**发送apijson数据 */
  PUBLISHER_API_JSON = 'PUBLISHER_API_JSON',
  /**创建发布者 */
  PUBLISHER_CREATE = 'PUBLISHER_CREATE',
  PUBLISHER_START = 'PUBLISHER_START',
  PUBLISHER_CLOSE = 'PUBLISHER_CLOSE',
  /**创建订阅者 */
  SUBSCRIBER_CREATE = 'SUBSCRIBER_CREATE',
  SUBSCRIBER_START = 'SUBSCRIBER_START',
  SUBSCRIBER_CLOSE = 'SUBSCRIBER_CLOSE',
  /**订阅关系 */
  SUBSCRIBER_SUBSCRIBE = 'SUBSCRIBER_SUBSCRIBE',
  SUBSCRIBER_UNSUBSCRIBE = 'SUBSCRIBER_UNSUBSCRIBE'
}

/**发送消息类型 */
export enum SendType {
  PUBLISHER_CLOSE = 'PUBLISHER_CLOSE',
  PUBLISHER_MESSAGE = 'PUBLISHER_MESSAGE',
  SUBSCRIBER_CLOSE = 'SUBSCRIBER_CLOSE'
}
