export enum MessageType {
  PUBLISHER_CREATE = 'PUBLISHER_CREATE',
  PUBLISHER_UPDATE = 'PUBLISHER_UPDATE',
  PUBLISHER_DELETE = 'PUBLISHER_DELETE',
  PUBLISHER_LIST = 'PUBLISHER_LIST',
  PUBLISHER_API_JSON = 'PUBLISHER_API_JSON',
  SUBSCRIBER_CREATE = 'SUBSCRIBER_CREATE',
  SUBSCRIBER_UPDATE = 'SUBSCRIBER_UPDATE',
  SUBSCRIBER_DELETE = 'SUBSCRIBER_DELETE',
  SUBSCRIBER_LIST = 'SUBSCRIBER_LIST',
  SUBSCRIBER_SUBSCRIBE = 'SUBSCRIBER_SUBSCRIBE',
  SUBSCRIBER_UNSUBSCRIBE = 'SUBSCRIBER_UNSUBSCRIBE',
}

export interface Message {
  type: MessageType;
  data: any;
  timestamp?: number;
}

export interface ResponseDTO {
  success: boolean;
  message: string;
  data?: any;
}
