version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: bridgehub_db_pg
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=hubcenter
      - POSTGRES_DB=bridgehub_db
    ports:
      - "5433:5432"
    restart: always
